version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: realestate
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/realestate
      - DOCKER_ENV=true
    depends_on:
      - db

volumes:
  postgres_data: